Disable crash reports entirely through macro
telegramdesktop/tdesktop pull request #16794
Opened 2021-08-10 21:05 UTC by mymedia2

This saves compile time and binary size. Guarding code by preprocessor is the only effective way to guarantee its elimination, even in most modern C++. And more importantly, one do not need to care of it for porting to old Qt.

2021-08-10 23:53 UTC, ilya-fedin commented
Why are you doing that?

2021-08-11 05:42 UTC, mymedia2 commented
@ilya-fedin I didn't ask you meaning of life

2021-08-11 14:42 UTC, john-preston requested changes
@mymedia2 I don't like the idea of doing this using preprocessor. I think there should be core/not_started_window module, that contains code without preprocessor that is always built and core/crash_report_window module, that uses this core/not_started_window module. core/crash_report_window module should be excluded from the build in CMake using remove_target_sources in case of crash reports not being used.

2026-09-05 18:08 UTC, ilya-fedin commented
Closing due to no changes in 2 years

2026-09-05 18:08 UTC, closed without merging