Control video in fullscreen mode using arrows and numbers
telegramdesktop/tdesktop pull request #16999
Opened 2021-09-23 17:17 UTC by Hermesiss

Following #6606

2021-09-23 17:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/telegramdesktop/tdesktop?pullRequest=16999) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/telegramdesktop/tdesktop?pullRequest=16999) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/telegramdesktop/tdesktop?pullRequest=16999) it.</sub>

2021-09-23 17:24 UTC, Aokromes commented
i don't think shortcuts doing different things between various parts of application is wise.

2021-09-24 03:28 UTC, Hermesiss commented
I can move it to a proper place. Number keys are processed in several places so I decided to put them with other media shortcuts

2021-09-25 11:52 UTC, john-preston requested changes
LGTM except some minor style changes.

2021-09-25 11:52 UTC, john-preston commented on Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
> +	Expects(_streamed != nullptr);
Please leave a newline after preconditions (`Expects(...)`)

2021-09-25 11:52 UTC, john-preston commented on Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
> +	crl::time newTime = std::clamp(_streamed->instance.info().video.state.position + time, 0LL, _streamed->instance.info().video.state.duration);
Please use `const auto ...` variable declaration where appropriate.

Also here the line length is too long, the rest of the codebase follows such style in such cases:
```cpp
const auto newTime = std::clamp(
    _streamed->instance.info().video.state.position + time,
    crl::time(0),
    _streamed->instance.info().video.state.duration);
```

2021-09-25 11:52 UTC, john-preston commented on Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
> +	Expects(_streamed != nullptr);
Please leave a newline after preconditions (Expects(...))

2021-09-25 11:52 UTC, john-preston commented on Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
> +			else if (key == Qt::Key_0) {
Please use code style consistent with other places, specifically here - place `else if` on the same line as the closing brace, like:
```cpp
} else if (...) {
    ...
} else if (...) {
    ...
}
```

2021-09-25 16:13 UTC, 23rd commented on Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
> +				seekRelativeTime(5000);
5000 ms can be moved to `constexpr auto`.

2021-09-25 16:14 UTC, 23rd commented on Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
> +	const auto newTime = std::clamp(_streamed->instance.info().video.state.position + time, 0LL, _streamed->instance.info().video.state.duration);
This line is still too long.

2021-09-25 16:16 UTC, 23rd commented
By the way style changes can be squashed with the first commit.

2021-09-25 17:07 UTC, 23rd commented on Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
> +	const auto newTime = std::clamp(_streamed->instance.info().video.state.position + time,
```suggestion
	const auto newTime = std::clamp(
		_streamed->instance.info().video.state.position + time, 
```

2021-09-25 18:49 UTC, john-preston requested changes
I think that's all :) Thank you.

2021-09-25 18:49 UTC, john-preston commented on Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
> +constexpr auto kSeekTimeMs = 5000;
The last small thing - please use 5 * crl::time(1000) here, that way it has the correct type with the format like in the rest of the codebase. Thanks.

2021-09-25 19:07 UTC, john-preston approved these changes
Ok, I've started the CI-s, when they build without problems I'll merge it for the next beta version.

2021-09-25 22:31 UTC, 23rd commented on Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
> +	progress = std::clamp(progress, 0., 1.);
```suggestion
	progress = std::clamp(progress, 0., 1.);
```

2021-09-25 22:33 UTC, 23rd commented on Telegram/SourceFiles/media/view/media_view_overlay_widget.cpp
> +	restartAtSeekPosition(_streamed->instance.info().video.state.duration * progress);
```suggestion
	restartAtSeekPosition(_streamed->instance.info().video.state.duration
		* std::clamp(progress, 0., 1.));
```

2021-09-26 04:51 UTC, Hermesiss commented
Please restart the CI (or see the previous [successful](https://github.com/telegramdesktop/tdesktop/actions?query=branch%3Avideo-keyboard-controls))

2021-09-26 10:07 UTC, merged

2021-09-26 10:07 UTC, john-preston commented
Thanks!