Introduce DESKTOP_APP_DISABLE_LEGACY_TGVOIP
telegramdesktop/tdesktop pull request #24126
Opened 2022-03-02 00:55 UTC by klemensn

Originally from Alt Linux[0], OpenBSD has so far adapted the removal of
tgvoip in the official net/tdesktop build.

tgcalls provides everything needed for calls;  audio/video/desktop
sharing calls have been working fine across different operating systems
and telegram desktop/mobile versions without problems.

0: http://www.sisyphus.ru/cgi-bin/srpm.pl/Sisyphus/telegram-desktop/getpatch/1

2022-03-02 01:19 UTC, ilya-fedin commented
> sharing calls have been working fine across different operating systems
> and telegram desktop/mobile versions without problems.

Even with Telegram X for Android? :thinking:

2022-09-20 10:58 UTC, rakino requested changes
Rebasing against these two commits is needed: https://github.com/telegramdesktop/tdesktop/commit/2b5d61ad36e96c46ff46793004e3ebc9d59535cb https://github.com/telegramdesktop/tdesktop/commit/84af084a3bc6408a11ad6da8b285b6b3792d739b

2022-09-20 11:01 UTC, ilya-fedin commented
There's no really need to, it was discussed in the tdesktop contributions group that there will be no possibility to build without libtgvoip. Either all tdesktop builds should support it until @john-preston decides it's the time to drop the support.

2022-09-20 11:19 UTC, rakino commented
Thanks for the explanation!

Another question is that, I wonder if there's a bugreport related to this issue mentioned in the packaging guide:
> so the calls will crash due to two webrtc libraries being in one address spacey

I didn't find that while searching through, would you mind giving me a pointer?

Thanks again :)

2022-09-20 11:29 UTC, ilya-fedin commented
This shouldn't ever happen if you let tdesktop to build libtgvoip. If you're trying to build libtgvoip with its own build scripts, it's unlikely to ever work right as they're abandoned.

2023-05-07 14:55 UTC, closed without merging