Add Right to Left capability to Telegram for languages like arabic, urdu and persian
telegramdesktop/tdesktop pull request #24467
Opened 2022-05-01 06:10 UTC by AMP999

2022-05-03 12:33 UTC, john-preston requested changes
Please use comments in the same way the comments appear in existing code:
```
// This is a comment.
p.thisIsMethod();
```

2022-05-03 12:33 UTC, john-preston commented on Telegram/SourceFiles/dialogs/dialogs_row.cpp
> +		rtl()
Better alignment looks like:
```
(rtl()
	? skip.x()
	: (st::dialogsPhotoSize - skip.x() - size)),
```

2022-05-03 12:33 UTC, john-preston commented on Telegram/SourceFiles/dialogs/dialogs_row.cpp
> +	).marginsRemoved({ shrink, shrink, shrink, shrink })); /**paints corener online or calling badge next to userpic in dialogs*/
Please put the comment lines above the code line, not to the right. Like:
```
// Paints corener online or calling badge next to userpic in dialogs.
q.drawEllipse(QRectF(
	st::dialogsPhotoSize - skip.x() - size,
	...
```

2022-05-03 12:33 UTC, john-preston commented on Telegram/SourceFiles/ui/unread_badge.cpp
> +	rtl()
Please use regular `if` in such cases.

2022-05-03 12:33 UTC, john-preston commented on Telegram/SourceFiles/window/window_connecting_widget.cpp
> +	}
Please put `else` on the same line, like `} else {`.

2022-05-03 13:17 UTC, AMP999 commented on Telegram/SourceFiles/window/window_connecting_widget.cpp
> +	}
Thank you. I'll fix them

2022-05-15 12:00 UTC, AMP999 commented
Why did snap ubuntu fail??

2022-05-15 12:18 UTC, 0363687994 commented
SMS 0939368520
***@***.***

Vào 19:01, CN, 15 thg 5, 2022 Amirreza Ashouri ***@***.***>
đã viết:

> Why did snap ubuntu fail??
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/telegramdesktop/tdesktop/pull/24467#issuecomment-1126922737>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AR64F5QNX3V6UYP4WM73HLLVKDRPXANCNFSM5UZMPGBQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-05-15 12:55 UTC, 0363687994 commented
0363686994
0939368520

Vào 19:18, CN, 15 thg 5, 2022 0363687994 ***@***.***> đã viết:

> SMS 0939368520
> ***@***.***
>
> Vào 19:01, CN, 15 thg 5, 2022 Amirreza Ashouri ***@***.***>
> đã viết:
>
> > Why did snap ubuntu fail??
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/telegramdesktop/tdesktop/pull/24467#issuecomment-1126922737
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AR64F5QNX3V6UYP4WM73HLLVKDRPXANCNFSM5UZMPGBQ
> >
> > .
> > You are receiving this because you are subscribed to this thread.Message
> > ID: ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/telegramdesktop/tdesktop/pull/24467#issuecomment-1126926536>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AR64F5SR2GX2Q2B7PA3EHHDVKDTSTANCNFSM5UZMPGBQ>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2022-05-18 06:32 UTC, AMP999 commented
I have resolved issues you mentioned in my code. Is there any problem in my code yet?
Thank you
@john-preston

2022-05-18 19:17 UTC, 23rd commented on Telegram/SourceFiles/dialogs/ui/dialogs_layout.cpp
> +				: unreadRight),
```suggestion
			(rtl() ? unreadLeft : unreadRight),
```

2022-05-18 19:17 UTC, 23rd commented on Telegram/SourceFiles/dialogs/ui/dialogs_layout.cpp
> +				: unreadRight),
```suggestion
			(rtl() ? unreadLeft : unreadRight),
```

2022-05-18 19:17 UTC, 23rd commented on Telegram/SourceFiles/dialogs/ui/dialogs_layout.cpp
> +				: nameleft),
```suggestion
			(rtl() ? (fullWidth - nameleft - availableWidth) : nameleft),
```

2022-05-18 19:17 UTC, 23rd commented on Telegram/SourceFiles/dialogs/ui/dialogs_layout.cpp
> +				: unreadRight),
```suggestion
			(rtl() ? unreadLeft : unreadRight),
```

2022-05-18 19:17 UTC, 23rd commented on Telegram/SourceFiles/dialogs/ui/dialogs_message_view.cpp
> +				? (geometry.left() + geometry.right() - rect.left() - _senderCache.maxWidth())
Please don't use `QRect::right()` method. It can be replaced with `geometry.left() + geometry.width()`.

2022-05-18 19:17 UTC, 23rd commented on Telegram/SourceFiles/dialogs/ui/dialogs_message_view.cpp
> +				? (geometry.left() + geometry.right() - rect.left() - st::dialogsMiniPreview)
Please don't use `QRect::right()` method. It can be replaced with `geometry.left() + geometry.width()`.

2022-05-18 19:17 UTC, 23rd commented on Telegram/SourceFiles/dialogs/ui/dialogs_message_view.cpp
> +			: rect.left()),
```suggestion
		(rtl() ? geometry.left() : rect.left()),
```

2022-05-18 19:17 UTC, 23rd commented on Telegram/SourceFiles/mainwidget.cpp
> +					: width() - thirdSectionWidth),
```suggestion
				(rtl() ? 0 : (width() - thirdSectionWidth)),
```

2022-05-18 19:17 UTC, 23rd commented on Telegram/SourceFiles/mainwidget.cpp
> +				: dialogsWidth),
```suggestion
			(rtl() ? thirdSectionWidth : dialogsWidth),
```

2022-05-18 19:17 UTC, 23rd commented on Telegram/SourceFiles/mainwidget.cpp
> +				: _history->x()),
```suggestion
			(rtl() ? _dialogsWidth : _history->x()),
```

2022-05-18 19:17 UTC, 23rd commented on Telegram/SourceFiles/mainwidget.cpp
> +				: _thirdSection->x()),
```suggestion
			(rtl() ? (width() - _thirdSection->width()) : _thirdSection->x()),
```

2022-05-18 19:17 UTC, 23rd commented on Telegram/SourceFiles/mainwidget.cpp
> +			: newWidth;
```suggestion
		newWidth = rtl() ? (width() - newWidth) : newWidth;
```

2022-05-18 19:17 UTC, 23rd commented on Telegram/SourceFiles/mainwidget.cpp
> +			: newWidth;
```suggestion
		newWidth = rtl() ? (width() - newWidth) : newWidth;
```

2022-05-18 19:17 UTC, 23rd commented on Telegram/SourceFiles/ui/unread_badge.cpp
> +					: rectForName.x() + qMin(nameWidth + st::dialogsScamSkip, rectForName.width() - width));
```suggestion

		const auto minWidth = std::min(
			nameWidth + st::dialogsScamSkip,
			rectForName.width() - width);
		const auto x = rtl()
			? (rectForName.x() + rectForName.width() - minWidth - width)
			: (rectForName.x() + minWidth);

```

2022-05-18 19:17 UTC, 23rd commented on Telegram/SourceFiles/window/window_connecting_widget.cpp
> +		st::connectingRight.paint(p, right, width());
```suggestion
		st::connectingLeftShadow.paint(p, rtl() ? right : left, width());
		st::connectingLeft.paint(p, rtl() ? right : left, width());
		st::connectingRightShadow.paint(p, rtl() ? left : right, width());
		st::connectingRight.paint(p, rtl() ? left : right, width());
```

2026-09-05 18:09 UTC, ilya-fedin commented
No changes for 3 years

2026-09-05 18:09 UTC, closed without merging