Fix build without QT_IMPLICIT_QCHAR_CONSTRUCTION
telegramdesktop/tdesktop pull request #28514
Opened 2024-10-10 18:17 UTC by K900

2024-10-10 18:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/telegramdesktop/tdesktop?pullRequest=28514) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/telegramdesktop/tdesktop?pullRequest=28514) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/telegramdesktop/tdesktop?pullRequest=28514) it.</sub>

2024-10-10 18:18 UTC, K900 commented
Other parts: 

- https://github.com/desktop-app/lib_ui/pull/245
- https://github.com/desktop-app/lib_base/pull/260
- https://github.com/desktop-app/codegen/pull/20
- https://github.com/desktop-app/cmake_helpers/pull/367

2024-10-11 05:11 UTC, john-preston requested changes

2024-10-11 05:11 UTC, john-preston commented on Telegram/SourceFiles/lang/lang_cloud_manager.cpp
> -		_switchingToLanguageId = -1;
This was a typo bug, it should be `_switchingToLanguageRequest = -1`, so that once `_api` is constructed this request would be resent.

2024-10-11 07:18 UTC, K900 commented on Telegram/SourceFiles/lang/lang_cloud_manager.cpp
> -		_switchingToLanguageId = -1;
Fixed

2024-10-11 07:46 UTC, john-preston commented
I've merged the submodules, can you please update them to the relevant commits (the ones from my repositories after PRs merge, not the ones you had in your forks) in this PR.

2024-10-11 07:48 UTC, K900 commented
Done

2024-10-11 09:59 UTC, john-preston commented
Thanks!

2024-10-11 10:44 UTC, K900 commented
I think https://github.com/desktop-app/lib_ui/commit/cfccb2de4d0e3045268276d0174f342ee5dd7e0f broke it.

2024-10-11 11:18 UTC, K900 commented
I think this should fix it.

2024-10-11 16:44 UTC, K900 commented
OK I think _this_ should fix it this time.

2024-10-12 15:54 UTC, merged