Build: Speed up third party libraries cloning
telegramdesktop/tdesktop pull request #28567
Opened 2024-10-23 20:03 UTC by difhel

When I tried to build Telegram Desktop from source code, I realized it was running pretty darn slow.

When I decided to look into it, I suddenly found out that the preparation script clones the entire git repository index of each third party library used, not just the last commit we need to build. So I looked at which stages `tdesktop` uses just a branch (without explicitly checkingout to a specific commit) and added the `--depth 1` parameter. This greatly reduces build preparation time, as well as disk space and traffic used, since some of the libraries used are very large.

2024-10-23 20:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/telegramdesktop/tdesktop?pullRequest=28567) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/telegramdesktop/tdesktop?pullRequest=28567) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/telegramdesktop/tdesktop?pullRequest=28567) it.</sub>

2024-10-24 10:11 UTC, john-preston commented
If this is to be added it should be non-default and somehow configurable, because I really enjoy full repository histories in the dependencies.

2024-10-26 15:43 UTC, ilya-fedin commented on docs/building-linux.md
> +    ./tdesktop/Telegram/build/prepare/linux.sh no-deps-git-history
This won't work, look at linux.sh

2024-10-26 15:45 UTC, ilya-fedin commented on docs/building-win.md
> +You might not need Telegram Desktop's git dependency history, in which case you can run this command and save disk space and speed up cloning quite a bit:
Maybe make it clear somehow that it has to be done instead of the last command? Given how much people ask stupid questions about build, I won't be surprised if people end up calling win.bat two times.

2024-10-26 15:46 UTC, ilya-fedin commented
Maybe squash 1st, 2nd and 4th commits?

2024-10-26 18:39 UTC, difhel commented on docs/building-linux.md
> +    ./tdesktop/Telegram/build/prepare/linux.sh no-deps-git-history
увы

2024-10-26 19:04 UTC, ilya-fedin commented on docs/building-win.md
> +> You might not need Telegram Desktop's git dependency history, in which case you can run this command **instead of the one above** and save disk space and speed up cloning quite a bit:
This seems clearer (imo)
```suggestion
> You might not need Telegram Desktop's git dependency history, in which case you can run this command **instead of the last one** and save disk space and speed up cloning quite a bit:
```

2024-10-26 19:15 UTC, ilya-fedin commented on docs/building-win.md
> +> You might not need Telegram Desktop's git dependency history, in which case you can run this command **instead of the one above** and save disk space and speed up cloning quite a bit:
Can you apply to other files?

2024-10-31 16:19 UTC, john-preston requested changes

2024-10-31 16:19 UTC, john-preston commented on Telegram/build/prepare/prepare.py
> +def git(command, args):
This does what I asked, but not the way other things are done here. It looks to me that more consistent with how the script already works would be another approach:
- if 'no-deps-git-history' is passed as an option you add something like 'DEPTH' -> '--depth 1' to the 'environment' map, otherwise set it to an empty string
- in all places necessary just add $DEPTH in the git command so that the '--depth 1' is added if necessary..

If this way it works as expected, then I'd like that approach to be implemented. If somehow I missed something and this doesn't work then we'll proceed with the one you proposed.

2026-09-05 18:17 UTC, closed without merging

2026-09-05 18:17 UTC, ilya-fedin commented
Conflicts